### ISSUE TITLE
Adapt to class-based req.context

### ISSUE THREAD

**Issue by vytas7** [zoltan-fedor/falcon-caching#1]
Hello @zoltan-fedor,
and thanks for porting/developing this caching component :+1: ! (And thanks for also adding it to our Wiki, that's the way I discovered it).

Btw, do not hesitate to join our [Gitter channels](https://falconframework.org/#sectionCommunity), such as [falconry/dev](https://gitter.im/falconry/dev) :wink:

Re this caching component, I just had a couple of notes which I thought filing as issues :slightly_smiling_face:

The first one comes here:
In Falcon 2.0, the default context type for [`req.context`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request.context) and [`resp.context`](https://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Response.context) was changed to a bare class, i.e. it is now preferred to write `req.context.cached = True` etc.

**Comment by zoltan-fedor** [comment]
Hi @vytas7,
Thanks for reporting this and all other issues!
I am still relatively new to the Falcon-world, I am coming over from Flask, so I might have missed some other things too. So please let them keep coming and I will try to fix them.

Thanks for the invite, I have joined the dev Gitter channel.

I have fixed this first issue - I have changed all `req.context` and `resp.context` to class instance attributes, see https://github.com/zoltan-fedor/falcon-caching/commit/3fcc6eceeb6768f9c0103398ff16f3ac38f8362a

Let me know if this doesn't address the issue you were seeing.
