### ISSUE TITLE
Response headers are not cached

### ISSUE THREAD

**Issue by vytas7** [zoltan-fedor/falcon-caching#2]
Unless I misinterpreted the middleware code, it seems that response headers are not cached:
https://github.com/zoltan-fedor/falcon-caching/blob/536faeee42fa2e13743f5ee87219c9a04a077892/falcon_caching/middleware.py#L64

This is probably fine as an MVP if documented as that could probably be patched in other middleware processing responses, but it seems that not even the `Content-Type` is cached, meaning all cached responses would use the default `Content-Type` (`application/json` in vanilla Falcon).

You could also take a look at my Falcon ASGI tutorial (which I hacked together very quickly a couple days ago, so don't expect super high quality, particularly the tutorial text is dull and repetitive), I was demoing a simple cache there: https://github.com/vytas7/falcon-asgi-example/blob/070d23306b2a15c7ad395f8ff72f01cf6ef4e5c4/asgilook/asgilook/cache.py#L27 (the concept could be easily extended to include all headers).

**Comment by zoltan-fedor** [comment]
Thanks. Yes, you are right, I am only caching the response body and nothing else.
I was mostly doing this so I don't need to do any additional serialization - and so avoiding the performance hit.

But you made a good point about the `Content-Type` header. For me it wasn't an issue, as I always use `application/json`, but loosing the `Content-Type` is definitely not a good default setting.

So I have made a change to keep the `Content-Type` header by default using the `msgpack` serialization just as you did, but also allowed turning this off with a new config setting named `CACHE_CONTENT_TYPE_JSON_ONLY`, so those who only use `application/json` doesn't need to take the perfomance hit of serializing and deserializing with `msgpack`.

See https://falcon-caching.readthedocs.io/en/latest/index.html#what-gets-cached
and https://github.com/zoltan-fedor/falcon-caching/commit/b7b69dfa14af14cc114ba636ffb98212b1d20190

I don't yet see a use case to cache all headers, but from this point on it would be easy. If somebody brings a use case for that in the future, then I will add that as a configurable option.

Thanks again!
