### ISSUE TITLE
Request body as cache key issues

### ISSUE THREAD

**Issue by vytas7** [zoltan-fedor/falcon-caching#3]
It is quite unusual for `GET` or `HEAD` requests to have a non-empty body at all, but even for cached responders that do handle the request body, the stream would have been emptied and left at EOF if completely consumed.

Therefore, either would these responders interfere with the cache key logic, or the cache middleware would consume the stream leaving nothing for requests.

Ref:
https://github.com/zoltan-fedor/falcon-caching/blob/536faeee42fa2e13743f5ee87219c9a04a077892/falcon_caching/middleware.py#L119

**Comment by zoltan-fedor** [comment]
Thanks.
Yes, I was wondering about this part for a while, whether it is worth including or not.
Based on your insight regarding the emptied stream not being available for the request, it doesn't worth it, so for now I will just remove the request body from the cache key and leave only the path and the method.
If later a request comes up to include the request body, then I will reconsider how to include it while avoiding emptying the stream (maybe refill it?) or maybe by storing it on the req.context to make it available to the responder.

See https://github.com/zoltan-fedor/falcon-caching/commit/5591191474fa2cd16759a301102f871a2340bd58
