### ISSUE TITLE
Responder name pattern logic could be refined in the cache decorator

### ISSUE THREAD

**Issue by vytas7** [zoltan-fedor/falcon-caching#4]
We have the same issue when applying Falcon hooks to a whole class, and our logic there is not bullet-proof either.

However, it is slightly more advanced than just checking `startswith('on_')`, we use this IIRC:
https://github.com/falconry/falcon/blob/8779753eaeb9be7313ae68eb43d82f0ba3a6cbb8/falcon/hooks.py#L25

**Comment by zoltan-fedor** [comment]
Great stuff, thanks!
I have missed that line in Falcon. I have added the same now, see https://github.com/zoltan-fedor/falcon-caching/commit/ea0c3eb780523dd7612cce90f288c3bc47f1e0ec
