### ISSUE TITLE
client.behaviors is missing

### ISSUE THREAD

**Issue by skrew** [zoltan-fedor/falcon-caching#5]
Hi,

I'm using `pylibmc` and the docs specify:

```# Break convention and set options on the _client object directly. For pylibmc behaviors: cache.cache._client.behaviors["tcp_nodelay"] = True``` 

But when i try to use it i got this error:

```AttributeError: 'Client' object has no attribute 'behaviors'``` 
 
I'm using the last version available (0.3.1)

**Comment by zoltan-fedor** [comment]
Thanks for raising this, unfortunately, I couldn't reproduce it.
I have just just create a test virtual env with Python 3.8 and the following packages:

```
Package        Version
-------------- -------
falcon         2.0.0
falcon-caching 0.3.1
msgpack        1.0.0
pip            20.1.1
pylibmc        1.6.1
setuptools     47.3.1
wheel          0.34.2
```

And executed the example code with no problem:
```
from falcon_caching import Cache

cache = Cache(
    config={
        'CACHE_TYPE': 'memcached',
        'CACHE_EVICTION_STRATEGY': 'time-based',
        'CACHE_MEMCACHED_SERVERS': ["127.0.0.1:11211",
                                    "127.0.0.1:11212"],
        'CACHE_KEY_PREFIX': 'cache'  # default: None
    })

# Break convention and set options on the _client object
# directly. For pylibmc behaviors:
cache.cache._client.behaviors["tcp_nodelay"] = True
```

Are you certain that you are using pylibmc? The `behaviors` attribute is only available for pylibmc, see http://sendapatch.se/projects/pylibmc/ and https://github.com/zoltan-fedor/falcon-caching/blob/a431aa9c09bb1140a9b97eda9cbeb839045fe4a9/falcon_caching/backends/memcache.py#L193 for picking the type of client to use. You can test by trying to import pylibmc directly to see whether any import errors are thrown:
`import pylibmc`

**Comment by skrew** [comment]
Ok my fault, i have `pip` installed `libmc` instead of `pylibmc`...

Why did I confuse the two libraries? No idea :)

**Comment by zoltan-fedor** [comment]
Hah, no worries!
