### ISSUE TITLE
falcon-caching/setup.py not found

### ISSUE THREAD

**Issue by bjliu** [zoltan-fedor/falcon-caching#6]
Running into an error when installing the latest version of falcon-caching

```
[appname/app app 1/1] RUN pip3 install -r requirements.txt --src /usr/local/src:
#23 0.254 + pip3 install -r requirements.txt --src /usr/local/src
#23 1.235 Collecting pynamodb (from -r requirements.txt (line 1))
#23 1.596   Downloading https://files.pythonhosted.org/packages/74/2b/524ffd7a9d2f816e0be468f38a6dd5fc737bd16cb1e907f1a34fd387906e/pynamodb-5.2.1-py3-none-any.whl (57kB)
#23 1.654 Collecting falcon==2.0.0 (from -r requirements.txt (line 2))
#23 1.954   Downloading https://files.pythonhosted.org/packages/19/30/edff5a1fea7a8e9876c8391e170263e1bb207875b6a65cd619818487b27b/falcon-2.0.0.tar.gz (397kB)
#23 2.466 Collecting falcon-caching (from -r requirements.txt (line 4))
#23 2.660   Downloading https://files.pythonhosted.org/packages/4d/cf/16666df8f3899194241bf1dfc04e6bb4e602ec3586b8dbea4e2cc55190ee/falcon-caching-1.0.1.tar.gz (78kB)
#23 2.879     Complete output from command python setup.py egg_info:
#23 2.879     Traceback (most recent call last):
#23 2.879       File "<string>", line 1, in <module>
#23 2.879       File "/usr/lib/python3.6/tokenize.py", line 452, in open
#23 2.879         buffer = _builtin_open(filename, 'rb')
#23 2.879     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-qbj_2599/falcon-caching/setup.py'
#23 2.879
#23 2.879     ----------------------------------------
#23 2.896 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qbj_2599/falcon-caching/
------
failed to solve: executor failed running [/bin/bash -xc pip3 install -r requirements.txt --src /usr/local/src]: exit code: 1
```

Our falcon version has been pinned to 2.0.0, wondering if that has anything to do with this failure.

**Comment by zoltan-fedor** [comment]
Hi @bjliu 
That is rather interesting.
I have just tried to install it into a new Python virtual env and I had no problems at all.

```
$ pip3 install falcon-caching
Collecting falcon-caching
  Downloading falcon_caching-1.0.1-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 KB 588.4 kB/s eta 0:00:00
Collecting falcon>=1.0.0
  Downloading falcon-3.1.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 8.1 MB/s eta 0:00:00
Collecting msgpack
  Downloading msgpack-1.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (322 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.2/322.2 KB 17.4 MB/s eta 0:00:00
Installing collected packages: msgpack, falcon, falcon-caching
Successfully installed falcon-3.1.0 falcon-caching-1.0.1 msgpack-1.0.3
``` 

It seems you are installing it in Docker. I will need steps to reproduce, as it doesn't reproduce by default.
Maybe you could write and share a Dockerfile which reproduces it?

**Comment by zoltan-fedor** [comment]
And yes, there is no `setup.py`, because this is packaged with `pyproject.toml`, see https://github.com/zoltan-fedor/falcon-caching

See more about `pyproject.toml` at https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

But that shouldn't matter for pip. 
Is it possible that you are not able to install packages with `pyprpject.toml` because you are using some ancient version of `pip`?
I recommend you add a step to your `Dockerfile` to update `pip` to a recent version before using it to install packages.

**Comment by zoltan-fedor** [comment]
I have added a shim `setup.py`, as it seems pip still requires that for editable installs. See https://stackoverflow.com/a/65162874
I don't see your install being an "editable install", but maybe this is another scenario where pip still requires a shim `setup.py`.

I have issued a new version, version 1.0.3. Try to install that.
Also make sure that your `pip` is in fact a recent version.

**Comment by bjliu** [comment]
I found out that this was a problem with pip version. I updated it and did not have any issues.

**Comment by zoltan-fedor** [comment]
Great, thanks for confirming!
