### ISSUE TITLE
Not seeing SSL key configuration in redis using falcon caching

### ISSUE THREAD

**Issue by romitojoseph-95** [zoltan-fedor/falcon-caching#8]
Not seeing SSL key configuration in redis using falcon caching

**Comment by zoltan-fedor** [comment]
While it was never tested with SSL Redis connection, using the `CACHE_REDIS_URL` parameter, you should be able to do just that.

See:
- `CACHE_REDIS_URL` param: https://falcon-caching.readthedocs.io/en/latest/#redis
- For constructing the Redis URL for SSL connection: https://github.com/redis/redis-py/issues/780#issuecomment-244786179 : 
`redis_url = 'rediss://h:PASSWORD@HOSTNAME:NNNN?ssl_cert_reqs=required&ssl_ca_certs=/path/to/custom/ca-cert' `
